# apiVersion: v1
# kind: Pod
# metadata:
#   name: kafka-go-client
#   namespace: kafka
# spec:
#   containers:
#   - name: client
#     image: us.gcr.io/ruckussgdc-rsa-builder/pixy-bench:pubsub
#     imagePullPolicy: Always
#     command:
#       - sleep
#       - infinity
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-go-client-deploy
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-go-client
  template:
    metadata:
      labels:
        app: kafka-go-client
    spec:
      containers:
      - name: client
        image: us.gcr.io/ruckussgdc-rsa-builder/pixy-bench:pubsub
        imagePullPolicy: Always
        command:
          - sleep
          - infinity