apiVersion: v1
kind: Service
metadata:
  name: mlisa-msg-svc
  namespace: kafka
spec:
  type: ClusterIP
  ports:
    - port: 19091
  selector:
    app: mlisa-msg-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlisa-msg-svc-dep
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlisa-msg-svc
  template:
    metadata:
      labels:
        app: mlisa-msg-svc
    spec:
      containers:
      - name: mlisa-msg-svc
        image: us.gcr.io/ruckussgdc-rsa-builder/kafka-producer-grpc:pubsub-2.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: Log.Verbose
          value: "true"
        - name: Kafka.Brokers
          value: kafka-0.kafka-headless-svc:9092,kafka-1.kafka-headless-svc:9092,kafka-2.kafka-headless-svc:9092
        - name: Proxy.Port
          value: "19091"
        - name: Pubsub.Timeout
          value: "60"
        ports:
        - containerPort: 19091
